### ISSUE TITLE
session-file-store + passport.socketio

### ISSUE THREAD

**Issue by flareofghast** [valery-barysok/session-file-store#12]
Hi,
I am trying to use your session-file-store and passport.socketio. It's all pretty new to me and so I am not sure where the issue really lies but thought you might be able to help me out.

I am getting 
````
[session-file-store] will retry, error on last attempt: SyntaxError: Unexpected end of input
````
in my console

I really don't know where to start to debug this. Here is how I have initialised the code

````
app.use(session({
			store: new sessionStore,
			secret: 'keyboard cat',
			key: 'express.sid',
			resave: true,
			saveUninitialized: true
			}));

io.use(passportSocket.authorize({
			cookieParser: cookieParser,       // the same middleware you registrer in express 
			  key:          'express.sid',       // the name of the cookie where express/connect stores its session_id 
			  secret:       'keyboard cat',    // the session_secret to parse the cookie 
			  store:        sessionStore        // we NEED to use a sessionstore. no memorystore please 
			}));
````
If you could five me some direction as to what needs to be fixed I would appreciate it. I can confirm the session folder exists and a session json file has been created.

**Comment by ndanson** [comment]
This is possibly due to simultaneous read/write I/O on the file. File locks might help in future releases.

**Comment by valery-barysok** [comment]
In most cases it is true and It is OK. If session file can not be read then you get message about it and read session file again while not succeed or attempts count is exceeded.
