### ISSUE TITLE
touch support (reset time to live)?

### ISSUE THREAD

**Issue by fourpixels** [valery-barysok/session-file-store#17]
Hi guys,
As I'm using this file storage, I'm unable to see any code that uses the `touch` functionality of `express-session`, so when the cookie `maxAge` is reached (via `ttl`), it's reaped, and so the session is gone.

Is this correct, or I'm missing something?
Thanks!

**Comment by valery-barysok** [comment]
Hi,
I'll see it in near future and fix it or you can do pull request if you want to get it asap and support this project.

**Comment by valery-barysok** [comment]
@fourpixels, please see 0.0.17 version. It has to work now.

**Comment by fourpixels** [comment]
Thanks for the update! Unfortunately I already switched to Redis based session store, as it had all I needed. Anyways - I can still use file storage locally if needed. The update seems great!
