### ISSUE TITLE
SyntaxError: Unexpected token } on session deserialization 

### ISSUE THREAD

**Issue by thepont** [valery-barysok/session-file-store#18]
The following error was occurring when the session-file-store was attempting to deserialise the session, 

        SyntaxError: Unexpected token }
            at Object.parse (native)
            at /Volumes/Source/auditr/node_modules/session-file-store/node_modules/fs-extra/node_modules/jsonfile/index.js:14:18
            at fs.js:272:14
            at /Volumes/Source/auditr/node_modules/session-file-store/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
            at Object.oncomplete (fs.js:108:15)

Deleting the session files did not resolve the issue, when the web browser went back to the application the resulting session had the same issue, restarting the browser, then doing a 'hard reload' in chrome _deleting chrome's session_ resolved the issue.

        {
          "cookie": {
            "originalMaxAge": null,
            "expires": null,
            "httpOnly": true,
            "path": "/"
          },
          "passport": {},
          "returnTo": "/api/lastfm/nowPlaying",
          "__lastAccess": 1438648699995,
          "flash": {}
        }
        }

Another application was previously running on the same port, and the session recorded `returnTo` refers to the previous application URL.

**Comment by valery-barysok** [comment]
can you reproduce this issue or did it happen one time? can you provide your package.json dependencies, node version, did you use any browser storages? if reproducible can you create minimum app with this issue?

**Comment by valery-barysok** [comment]
@thepont, it will be helpful to get more information.

**Comment by thepont** [comment]
Sorry about the late response, It just happened one time, I will see if I can reproduce it at work on Monday.

**Comment by valery-barysok** [comment]
thanks, will wait

**Comment by thepont** [comment]
I was able to reproduce, node version is v0.10.35, I haven't had a change to make a small app to reproduce the issue.

It seems to happen the following way, I have two Project 1 and Project 2, Project 1 polls the server for updates from endpoints, when it get an update it then renders it. If I run project 1 and leave it open, then kill project 1 then open project 2, project 2 gives the previous error when the webpage from project 2 attempts to poll and get information, this then happens from that time forward each time project 2 is requested from the browser that had project 2 open.

##Project 1.

	  "dependencies": {
	    "autoprefixer-core": "^5.2.0",
	    "bamboo-api": "0.0.5",
	    "bd-stampy": "^0.1.30",
	    "circleci": "^0.2.0",
	    "commander": "^2.6.0",
	    "cookie-parser": "^1.3.5",
	    "css-mqpacker": "^3.1.0",
	    "csswring": "^3.0.5",
	    "dotenv": "^1.2.0",
	    "elephas": "^0.1.20",
	    "es5-shim": "^4.1.5",
	    "es6-promise": "^2.1.1",
	    "express": "^4.12.4",
	    "express-handlebars": "^2.0.1",
	    "express-session": "^1.11.2",
	    "github": "^0.2.4",
	    "grunt": "^0.4.5",
	    "grunt-browser-sync": "^2.0.0",
	    "grunt-concurrent": "^1.0.0",
	    "grunt-contrib-concat": "^0.5.1",
	    "grunt-contrib-sass": "^0.9.2",
	    "grunt-contrib-watch": "^0.6.1",
	    "grunt-nodemon": "^0.4.0",
	    "grunt-postcss": "^0.3.0",
	    "grunt-webpack": "^1.0.8",
	    "immutable": "^3.7.3",
	    "jit-grunt": "^0.9.1",
	    "json-loader": "^0.5.2",
	    "jsx-loader": "^0.12.2",
	    "jsxstyle": "0.0.13",
	    "lastfm": "^0.9.2",
	    "lodash": "^3.9.3",
	    "moment": "^2.10.3",
	    "natural": "^0.2.1",
	    "node-jsx": "^0.12.4",
	    "node-libs-browser": "^0.5.2",
	    "nodemon": "^1.3.7",
	    "pixrem": "^1.2.0",
	    "pos": "^0.2.0",
	    "react": "^0.12.2",
	    "react-router": "^0.12.4",
	    "react-tools": "^0.12.2",
	    "reflux": "^0.2.7",
	    "reflux-immutable": "^1.0.1",
	    "socket.io": "^1.3.6",
	    "superagent": "^0.21.0",
	    "tabletop": "^1.4.2",
	    "tunic": "git://github.com/allanhortle/tunic",
	    "webpack": "^1.9.10",
	    "webpack-dev-server": "^1.7.0"
	  }

##Project 2.
	 
	 "dependencies": {
	    "bcrypt": "^0.8.2",
	    "bd-stampy": "^0.1.73",
	    "bruce": "0.0.6",
	    "classnames": "^1.2.2",
	    "elephas": "^0.2.0",
	    "es6-promise": "^2.1.0",
	    "express": "^4.12.3",
	    "express-session": "^1.11.2",
	    "immutable": "^3.7.2",
	    "install": "^0.1.8",
	    "jsx-loader": "^0.13.1",
	    "jsxstyle": "0.0.14",
	    "lodash": "^3.8.0",
	    "mandrill-api": "^1.0.45",
	    "marked": "^0.3.3",
	    "moment": "^2.10.2",
	    "mongodb": "^2.0.28",
	    "node-jsx": "^0.13.3",
	    "npm": "^2.10.0",
	    "passport": "^0.2.1",
	    "passport-local": "^1.0.0",
	    "react": "^0.13.2",
	    "react-engine": "^1.7.0",
	    "react-modal": "^0.2.0",
	    "react-router": "^0.13.2",
	    "react-select": "^0.5.1",
	    "react-tap-event-plugin": "^0.1.6",
	    "reflux": "^0.2.7",
	    "reflux-immutable": "^1.0.1",
	    "request": "^2.57.0",
	    "route-pattern": "0.0.6",
	    "session-file-store": "0.0.16",
	    "slug": "^0.9.1",
	    "superagent": "^1.2.0",
	    "trc_styles": "git://github.com/blueflag/trc_styles.git#v1.0.4",
	    "url-pattern": "^0.9.0",
	    "radium": "^0.13.2"
	  }

**Comment by valery-barysok** [comment]
thanks, will see how to fix

**Comment by valery-barysok** [comment]
after some investigation i can not chance to reproduce it.

**Comment by unreadableusername** [comment]
I have same issue with session saving and reading
writeJson method saves broken json very often

as temporary fix I've changed session-file-helpers.js:170 file

```fs.writeJson(sessionPath, session, function (err) {```
to 
```fs.writeFile(sessionPath, JSON.stringify(session), function (err) {```
and now it's working fine
looks like writeJson method is broken

**Comment by valery-barysok** [comment]
great help, thanks ) will update code with your fix.

**Comment by valery-barysok** [comment]
Just looked at implementation of writeJson. The only difference between your solution and existing function is 

```js
    // writeJson:
    str = JSON.stringify(obj, options ? options.replacer : null, spaces) + '\n'
   // str = JSON.stringify(obj, null, 2) + '\n'
```
and

```js
   str = JSON.stringify(obj)
```
Can you provide more details about what node version do you use?

**Comment by unreadableusername** [comment]
@valery-barysok 
Yes, but before this change I've got such error a lot of time(almost everytime) and after this change no errors

I've checked on 0.10, 0.12, 4.0, 4.1, 4.1.1

**Comment by valery-barysok** [comment]
@unreadableusername, i just published new version with provided fix.
