### ISSUE TITLE
Illegal invocation

### ISSUE THREAD

**Issue by peze** [valery-barysok/session-file-store#25]
i have used the session-file-store,a very nice moudle...but sometimes the illegal invocation error will occur.like this
<pre>
TypeError: Illegal invocation
    at /Users/jay/peze/ams-pc-node/node_modules/session-file-store/lib/session-file-helpers.js:63:19
</pre>
..it makes me very puzzle....

i use the session-file-store like that
<pre>
var session = require('express-session');
var FileStore = require('session-file-store')(session);
app.use(session({
        secret:"fdsgsdfgsd",
        store: new FileStore({
            path:'./session_file',
            ttl: 30*24*3600*1000
        }),
        resave: true,
        name:"MC-AMS-PC",
        saveUninitialized: true
    }
));
</pre>

**Comment by valery-barysok** [comment]
can you check if does options.logFn function exist in this situation?

**Comment by valery-barysok** [comment]
try latest version if it works correct
