### ISSUE TITLE
File reaping prevents graceful server shutdown

### ISSUE THREAD

**Issue by janmeier** [valery-barysok/session-file-store#27]
With the [example app](https://github.com/valery-barysok/session-file-store/blob/e4edac9d5da3a2d6be832a72d78febb952f2eadb/examples/express-example/app.js)

Add a `setTimeout`, which calls `server.close()` after x seconds. 

I expected the script to stop, but unfortunately it hangs. This is due to the `setInterval` call [here](https://github.com/valery-barysok/session-file-store/blob/e4edac9d5da3a2d6be832a72d78febb952f2eadb/lib/session-file-helpers.js#L61-L69). Because the interval is still active, the process won't end. I've tested saving the interval to a variable and calling `clearInterval`, and when doing that the script exists fine.

The problem then is to determine when to do that. The ideal would be `server.on('close')`, but we don't have access to `server` object - And we can't pass it as an option to `FileStore`, because the store has to be initalized before calling `app.listen`, which returns `server`. For now I've resolved to manually calling `process.exit` to make my tests exit

Any ideas? 

Tested on node 0.12 and 4

**Comment by valery-barysok** [comment]
I added reapIntervalObject as out parameter in options object. You can try to use like:

```js
var options = {
  store: new FileStore,
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true
};

app.use(session(options));

...

server.on('close', function () {
  if (options.reapIntervalObject) {
    clearInterval(options.reapIntervalObject);
  }
});
```
