### ISSUE TITLE
session_file/02iVfxbA2m1Bd09jatpBBdi1nSbXTJGR.json Unexpected token I

### ISSUE THREAD

**Issue by angelina999990** [valery-barysok/session-file-store#29]
I am using session-file-store for login. Sometimes get this Problem. And it's' hard to reproduce it. 
Could anybody tell what caused it?
Pretty sure I did not write session_file manually.

**Comment by valery-barysok** [comment]
Can you provide file where this issue happened?

**Comment by valery-barysok** [comment]
@angelina999990, Can you provide the `02iVfxbA2m1Bd09jatpBBdi1nSbXTJGR.json` file where this issue happened?

**Comment by angelina999990** [comment]
@valery-barysok  It happened a fews days ago. I tried to look the file but it  already lost :(

**Comment by valery-barysok** [comment]
@angelina999990, when it happens again then provide it here. thanks)
