### ISSUE TITLE
Session file truncated after fatal exception

### ISSUE THREAD

**Issue by erg0dic** [valery-barysok/session-file-store#31]
If my application is taken down by an unhandled exception, I get the following error when trying to load the session:

```
[session-file-store] will retry, error on last attempt: SyntaxError: Unexpected end of input
```

I see on disk that the file has been truncated to 0 bytes.

Other details:
OS X El Capitan 10.11
Session is in /var/tmp/

**Comment by erg0dic** [comment]
Please consider using write-file-atomic instead of fs.writeFile:
https://www.npmjs.com/package/write-file-atomic

**Comment by valery-barysok** [comment]
@erg0dic, thanks for your suggestion. It will be great if you can do pull request with required changes. If not then I need some time to consider this solution.

**Comment by valery-barysok** [comment]
@erg0dic, i added using write-file-atomic instead of fs.writeFile. new version is 0.1.0
