### ISSUE TITLE
SyntaxError: tmp/sessions/gAFEKQ7YgLKzvvzoye9mre9e8DvKkXXX.json: Unexpected token i<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at /Users/.../node_modules/session-file-store/node_modules/fs-extra/node_modules/jsonfile/index.js:14:18<br> &nbsp; &nbsp;at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

### ISSUE THREAD

**Issue by orafaelreis** [valery-barysok/session-file-store#32]
I'm getting this error when I do login/logout more than one times. This happens cause session file contains an invalid json. Something like:

{
	"cookie": {
		"originalMaxAge": null,
		"expires": null,
		"httpOnly": true,
		"path": "/"
	},
	"datauser": {
		"id": 12,
		"name": "Some name"
	},
	"__lastAccess": 1454079643812,
}
ity ":" Belo Horizonte ","
}
}

It's clear to me that in some point some writeFile method is overriding the content wrongly.

Thanks in advance if someone help me!

**Comment by valery-barysok** [comment]
do you use version above 0.0.20?

**Comment by orafaelreis** [comment]
yeah, We're using 0.0.22.

**Comment by valery-barysok** [comment]
@orafaelreis, did you solve this issue? or can provide simple example that reproduce this issue?

**Comment by valery-barysok** [comment]
but i believe latest version has to solve this issue indirectly by using write file atomic to write session to separate file and then just rename it.
