### ISSUE TITLE
Error recovering session

### ISSUE THREAD

**Issue by damarna85** [valery-barysok/session-file-store#33]
Hi,

I have a weird behaviour in one of our servers. The same code works differently depending on the server the app is deployed. In one of the servers, the session is recovered without problems and working like a charm. The same happens in my local machine. However, in one of our production servers every time I request the session I am receiving the following error:

[session-file-store] will retry, error on last attempt: Error: ENOENT, open 'sessions/Z6Ncz1p8gnsK2_w67EkAmz0VCZ0kAUIX.json'

And no session is recovered. As the code is the same, it looks some problem with permission or something. I also noticed that in the environment where the module does not work there are much more json files than in the one it works.

Any hint on this?

Thank you very much in advance.

**Comment by mpaezmolina** [comment]
Same thing happening to me. What could be the root problem? Because I think that is a generic error message that also is shown when there is a collision reading the file, but clearly this is not the case.

**Comment by valery-barysok** [comment]
Can you reproduce it with some docker container that i can run?

**Comment by damarna85** [comment]
Hi Valery,

We finally found out that the production server was in cluster and we were
not aware of that. That explains the issue and obviouslly is not a bug on
your side.

Thanks!
