### ISSUE TITLE
error in cleaning expired sessions

### ISSUE THREAD

**Issue by enricod** [valery-barysok/session-file-store#39]
the file reap-worker calls helpers.reap without passing a callback function.
In sessions-file-helpers.reap, if an error is occured the callback is invoked but it's undefined

**Comment by valery-barysok** [comment]
can you give me more details about this issue?

 There is next code:

     reap: function (options, callback) {
          callback || (callback = function () {
          });

Why does it not work for you?

**Comment by Ste1990** [comment]
Ok, my bad, I still have a problem on my server after the "cleaning sessions process" but I didn't see the assignement of "callback", I thought that could be the error

**Comment by valery-barysok** [comment]
What kind of problem? is node instance terminated or what?

**Comment by Ste1990** [comment]
I don't know what kind of problem is yet, but the node instance terminates repetedly, and the last log I can see is the one that tells the process "cleaning expired session" is running

**Comment by valery-barysok** [comment]
sorry but I can not help without more details. Can you try make dependency on your fork version of session file store with callback function you provided before in pull request? May be you will get more details about this issue if it is really there.

**Comment by valery-barysok** [comment]
no additional details.
