### ISSUE TITLE
Callback function when sessions are deleted.

### ISSUE THREAD

**Issue by ursLegit** [valery-barysok/session-file-store#47]
I think a way  to define a function that would be called when sessions are deleted automatically would be really helpful. It would make it easier to update database etc. when session are expired.

**Comment by valery-barysok** [comment]
@ursLegit, do you have any ideas how to implement this feature?

We can detect that session is expired on next request that can never happen. Also we reap all expired sessions on cleanup process (can be executed as distinct process on regular bases) and you can delete all sessions by hands. From my point of view we have a lot of troubles with required callback. So all described situations can be done directly in your application. I think it will be the best decision.

But i am open for suggestions. So feel free to comment. thanks
