### ISSUE TITLE
encrypt option: Bad implementation

### ISSUE THREAD

**Issue by gk0us** [valery-barysok/session-file-store#49]
As @TYoung86 mentioned [here](https://github.com/valery-barysok/session-file-store/pull/28) the encrypt option is badly implemented.

> `encrypt` Enables encryption of the session before writing the file and also decryption when reading it.
encrypt description from README.MD

The encryption algorithm used is AES-256-CTR and the encryption key used per JSON file is the sessionID\[1\]\[2\].  Therefore, it seems that the encryption key for each JSON file’s content is the filename itself, beating the whole purpose of encrypting the session data. Whoever has access to the JSON files can also decrypt the contents using the respective filenames.

Developers that use this middleware may be misled to believe that, by setting `options.encrypt` to `true`, they will achieve a form of confidentiality over the session data in storage, which apparently is not the case.

**Recommendation:**
Use a Master-key, which will derive "per session" keys combining the sessionID (salting)

@TYoung86 's [PR](https://github.com/valery-barysok/session-file-store/pull/45/files)  provides the tools for such a functionality by defining a  keyFunction.

My only objection is that when `encrypt` is used, it should not default to using just the sessionID as the encryption key. A default key-function should be provided (obviously not the `function(s){return s;}` ), which will implement the above recommendation.

**Note** that the README.MD file must be updated to inform developers about the current implementation of `encrypt` and the security considerations.

\[1\]: https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L192
\[2\]: https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L321

**Comment by valery-barysok** [comment]
@gk0us, I published new version (1.0.0) with merged PRs and with updates according to your recommendations. Can you review? Thanks

**Comment by TYoung86** [comment]
The issue with changing the default functionality requires some way to prevent breakage and maybe migrate previous configurations or at least provide a warning. A start-up test for a marker file in the directory or some such.

**Comment by TYoung86** [comment]
A basic example of the "master key" mentioned is used in a test case, and I see it has been extended to incorporate a secret. The readme will need to reflect the new default function and signature of keyFunction.

As long as the default secret is an empty string then that should still be backwards compatible.

**Comment by valery-barysok** [comment]
@TYoung86, adding "secret" provides almost the same user experience as you have with "secret" from express-session. in the same time key function extends it functionall.

**Comment by TYoung86** [comment]
Current implementation LGTM, @gk0us ?
