### ISSUE TITLE
File empty and message error

### ISSUE THREAD

**Issue by anddimario** [valery-barysok/session-file-store#5]
Hi, i've this issue:
[retry] will retry, error on last attempt: SyntaxError: Unexpected end of input
and sessions files sometimes are empty, have you some informations about that?

Thanks for your time
Best regards

**Comment by valery-barysok** [comment]
Hi
this message talks that you have concurrent access to session file. While write operation is updating file another read operation is trying to read content of this file and it can be invalid (empty). To resolve it you can increase 'retries' from 5 to another value. Also you can change 'factor', 'minTimeout' and 'maxTimeout' retry settings to fit your needs.
