### ISSUE TITLE
Error renaming session files on windows 10

### ISSUE THREAD

**Issue by loudking** [valery-barysok/session-file-store#51]
Hello I recently encounter this problem on Windows 10 and session-file-store v1.0.0. I have full control over the sessions folder but still get error like

Error: EPERM: operation not permitted, rename 'fullpath\sessions\random.json.random' -> 'fullpath\sessions\random.json'

Please suggest what to do.

**Comment by valery-barysok** [comment]
Hey.
can you provide settings that you used for this case? location on your file system. Did you try execute application with command "run as administrator"?

**Comment by loudking** [comment]
Hi I have sent my settings and tracing to you via email. Please check.

**Comment by valery-barysok** [comment]
issue relates to relax transitive dependency on graceful-fs. It fails with 4.1.11 version. So you need to lock version on 4.1.10 (npm install graceful-fs@4.1.10 --save in your project and change from "^4.1.10" to "4.1.10")

**Comment by xcapt** [comment]
Hi there,
We are also using also the module, and have the same EPERM issue lately, thus I was trying to do the below:

> issue relates to relax transitive dependency on graceful-fs. It fails with 4.1.11 version. So you need to lock version on 4.1.10 (npm install graceful-fs@4.1.10 --save in your project and change from "^4.1.10" to "4.1.10")

However write-file-atomic is explicitly asking for 4.1.11, thus maybe session-file-store should use a previous version of write-file-atomic ?

**Comment by valery-barysok** [comment]
@xcapt, i thought about it and i am going to do the same way as you suggested. So just wait for update until provided workaround has to work (it worked for me with flat dependencies when i tested it before)

**Comment by xcapt** [comment]
thanks for the quick response !

**Comment by ma-zal** [comment]
Caused by issue https://github.com/isaacs/node-graceful-fs/issues/104

**Comment by valery-barysok** [comment]
lock write-file-atomic version to 1.3.1

**Comment by ferm10n** [comment]
@valery-barysok, or anyone interested
Can you check to see if write-file-atomic@2.3.0 resolved this issue?

I submitted a PR addressing this issue, which was just recently included. https://github.com/npm/write-file-atomic/pull/22

If it doesn't help completely, then im pretty sure the writes to a session will need to be serialized

**Comment by AleCaste** [comment]
I tried to replace write-file-atomic with v2.3.0 and was still getting the errors on Windows 7.
I then replaced graceful-fs with v4.1.10 and again, no joy.
Recently I heard of the module [connect-loki](https://www.npmjs.com/package/connect-loki) which also writes the sessions to json files (it uses [LokiJs](http://lokijs.org) datastore internally which I never heard of before) and so far it's doing the job incredibly well.
So for those of you running into these EPERM problems on Windows machines I suggest you check ```connect-loki``` out.

**Comment by wizardbluebolt** [comment]
As follow up to my comment above, I am also sometimes still seeing both the EPERM and ENOENT exceptions on Windows 10 unfortunately.  The issues are intermittent, and my initial positive result did not pan out after more extensive testing.  Thanks very much for the alternative to consider!

**Comment by wizardbluebolt** [comment]
connect-loki is working well for me also so far, and a very easy change to make.  Thanks again.

**Comment by AleCaste** [comment]
I am glad to hear that. I still would have preferred the approach of having a separate json file per session (session-file-store) rather than a single json database file (connect-loki) since I can imagine the performance on the 2nd approach will be worse when dealing with high request volumes (=many new sessions and thus many file re-saves if you have a single file database) but in normal scenarios it does the job quite well.
These EPERM problems on Windows have been a constant on session-file-store module and it seems to me no-one has tried to address the issue seriously. What a pity!
