### ISSUE TITLE
Can't set number of retries to 0

### ISSUE THREAD

**Issue by takkaria** [valery-barysok/session-file-store#56]
If I set the number of retries to 0, then [session-file-helpers.js:59](https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L59) sets it to 5, since `0 || 5` evaluates to `5`.

I suggest using Object.assign() for defaults instead of the || notation, since it will notice that the property is set, so e.g.:

```javascript
function defaults(options) {
  const defaults = {
    retries: 5,
    factor: 1,
    // etc
  };

  return Object.assign({}, defaults, options);
}
```

npm package [object-assign](https://www.npmjs.com/package/object-assign) provides this functionality for later Node before version 4.

**Comment by valery-barysok** [comment]
@takkaria, thanks for suggestion.

Can you provide pull request with this fix?

**Comment by takkaria** [comment]
I will work on one.
