### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by luckyqiao** [valery-barysok/session-file-store#58]
Hi! I use this module in my app. Sometimes it throws Error` "Error: EPERM: operation not permitted, rename '6iU7HYN8jOSY-Biqpv5uRZT_I-AAgTkA.json.1374059317' -> '6iU7HYN8jOSY-Biqpv5uRZT_I-AAgTkA.json' at Error (native)"`. Then my app will stop running, even I ran app as Administrator.
This is my environment:

- OS: Windows 7
- node version: 6.9.5
- express: 4.x

Thanks!

**Comment by valery-barysok** [comment]
do you have concurrent renaming (operations) in this moment?

**Comment by luckyqiao** [comment]
@valery-barysok no, this is my code:
```
var session = require('express-session');
var FileStore = require('session-file-store')(session);
app.use(session({
    resave:false,
    saveUninitialized:true,
    store: new FileStore({ttl:18000}),
    secret: '123456'
}));
```

I use this module as session store in my app, and after a few request, this error will happen..

**Comment by jkurei** [comment]
I have the very same bug, except it doesn't happen sometimes, but every time. Is there no fix?

Did you find any work-around, @luckyqiao ?

Thanks!

**Comment by valery-barysok** [comment]
@jkurei, see https://github.com/valery-barysok/session-file-store/issues/51
