### ISSUE TITLE
Sessions not deleted?

### ISSUE THREAD

**Issue by jpjpjp** [valery-barysok/session-file-store#59]
What is the right way to "cleanup" sessions?  Im finding that the files in my ./sessions directory never seem to go away.

I initialize as follows:
var sessionMiddleware = session({
  name: 'server-session-cookie-id',
  secret: 'my express secret',
  reapInterval: 60 * 5,  // reap sessions after 5 minutes
  saveUninitialized: false,
  resave: false,
  store: new FileStore()
});

I can start a new session.  Close the browser tab and observe that the new session is not reaped after 5 minutes.

Also, is there a best practice way to "clean up" sessions when restarting the server?  In my case I'm not interested in persistence in this case.   So for example if i have 10 sessions going, I hit ctrl-c to kill the server, and then restart it later, can those 10 sessions be reaped?  If I manually delete them the system complains about missing them.

**Comment by valery-barysok** [comment]
@jpjpjp, why do you think that session has to be reaped after five minutes? i think your session cookie has much longer expiration period. and if you deleted session files manually but got message about missed file then your session cookie was not expired yet.
