### ISSUE TITLE
don't working anymore with chrome when using dependency write_file_atomic@1.3.4

### ISSUE THREAD

**Issue by miouge** [valery-barysok/session-file-store#61]
Hello
can't explain really why but my cloud app was working
using session-file-store@1.0.0 using as dependency write_file_atomic@1.3.1
and is not working anymore 
using session-file-store@1.0.0 using as dependency write_file_atomic@1.3.4

the problem appear only when using chrome but not firefox (very strange, but very reproductible)
symptoms are that passport object are not deserialized into req.user.

just uninstalling the write_file_atomic@1.3.4 and install the write_file_atomic@1.3.1 package fix the problem
our nodeJs server on linux used also for authentification
passport@0.3.2
passport-local@1.0.0
express@4.15.2
express-session@1.15.1
hope this can help others.

I beg your pardon for my poor language level (i'm french)

Philippe

**Comment by DonMartin76** [comment]
Hello @miouge, this greatly helped me. All of a sudden, I got this really strange misbehaviour that sessions did not seem to be persisted, or, in some cases, later (not reproducible). It did not even seem tied to a browser, but probably rather to a specific runtime, such as Docker or non-Docker.

Pinning `write-file-atomic` to `1.3.1` in **my** `package.json` helped me, as `npm` then re-uses that version for `session-file-store`. See Haufe-Lexware/wicked.haufe.io#72. I will file an issue with that package as well.

**Comment by valery-barysok** [comment]
lock write-file-atomic version to 1.3.1

**Comment by iarna** [comment]
I encourage you all to try `write-file-atomic@2.3.0` which serializes access to the same file. (The breaking change in 2.0.0 was dropping support for 0.10 and 0.12.)

**Comment by T3charmy** [comment]
Forcing `write-file-atomic` to v2.3.0 fixed it for me!

**Comment by valery-barysok** [comment]
@T3charmy, great! will update dependency in near future.
