### ISSUE TITLE
NodeJS Warning "Use Cipheriv for counter mode of aes-256-ctr"

### ISSUE THREAD

**Issue by Yoshiin** [valery-barysok/session-file-store#65]
Hello. 
Since nodejs 8.x, crypto is checking the encoding algorithm used for crypto.createCipher().
It's possible to change your encoding algorithm to 'aes-256-gcm' or externalize this configuration ? 

Thanks,

**Comment by Mindgames** [comment]
Same issue here

![image](https://user-images.githubusercontent.com/2171273/32689569-abc81304-c6e7-11e7-805b-4ab950279714.png)

**Comment by igor9silva** [comment]
Same here. v8.7.0

**Comment by clakech** [comment]
any way to disable those warnings ?

**Comment by Yoshiin** [comment]
It’s a Node warning about security, so, no, you can’t disable it. 
If you want you can edit lib/session-file-helpers.js and change the encryption method by one suported by your server. 
This is an alternative way waiting for an owner update.

**Comment by clakech** [comment]
You can disable node warnings using --no-warnings or with env var NODE_NO_WARNINGS=1

cf: https://nodejs.org/api/cli.html

**Comment by igor9silva** [comment]
@clakech however It's not recommended.

The warning exists for a reason.

**Comment by clakech** [comment]
of course use with caution but there are some code that breaks because of this warning now in V8, so as a workaround you can disable those warnings at least. Fixing transitives dependencies that leads to this warning is not so easy and can be quite long.

For instance the vsts-tasks project is broken using node 8 now https://github.com/Microsoft/vsts-tasks

**Comment by valery-barysok** [comment]
See 1.2.0 version.

**Comment by amenadiel** [comment]
Should we set `options.encryptEncoding` to something different than 'hex' ?

**Comment by techmonkvivek** [comment]
used cipheriv still not working

**Comment by bahadir-be** [comment]
I have similar issue

**Comment by jas-** [comment]
@techmonkvivek @bahadir-be this is such an old and closed issue. 2018? Are you using an old version of this module? Or worse, node.js?

The latest version (1.5.x) no longer uses the same code base. As such the [default algo](https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L63) is no longer using the antiquated 'CTR' mode which would prevent node.js v8 from throwing the warning.

The latest LTS for node.js is v16 and from what I understand is that v8 is no longer being patched etc.

**Comment by bahadir-be** [comment]
> @bahadir-be this is such an old and closed issue. 2018? Are you using an old version of this module? Or worse, node.js?
> 
> The latest version (1.5.x) no longer uses the same code base. As such the [default algo](https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L63) is no longer using the antiquated 'CTR' mode which would prevent node.js v8 from throwing the warning.
> 
> The latest LTS for node.js is v16 and from what I understand is that v8 is no longer being patched etc.

indeed.. fixed now.
Thanks for your feedback.
