### ISSUE TITLE
 store.set  results to callback is not a function

### ISSUE THREAD

**Issue by japheth-waswa** [valery-barysok/session-file-store#70]
session-file-helpers.js:222
          err ? callback(err) : callback(null, session);
                ^
TypeError: callback is not a function

Getting above error inside socket
================code=====================

socket.on('socketStartUpCst', function (data) {

cookiesStr = socket.handshake.headers.cookie || socket.request.headers.cookie;
        var cookies = cookie.parse(cookiesStr);
        ciSessionCookie = cookies.ci_session;
        console.log(cookies);
        sidFull = cookies["connect.sid"];

session.myNames="jane doe";

      store.set(sidFull,session,options,function(err){
              console.log("add start");
            console.log(session);
            console.log("add end");
        });

    });

**Comment by valery-barysok** [comment]
do you resolve your issue?
can you provide more information if possible? (node version, write-file-atomic package version, etc)
sorry for long delay.

**Comment by valery-barysok** [comment]
issue relates to incorrect usage of `function (sessionId, session, callback)`. In provided code snippet there are 4 parameters instead of 3.
