### ISSUE TITLE
session-file-store prevents test suite from exiting

### ISSUE THREAD

**Issue by Tilogorn** [valery-barysok/session-file-store#72]
After introducing tests to my Node.js project with `mocha` I noticed that the test suite can't exit after executing all the tests. The terminal "hangs" in the mocha execution. Expected behaviour is that the tests run and the terminal returns to a new prompt.  I stripped it down to `session-file-store` which causes the terminal to hang.

# Steps to reproduce

## Install vanilla session-file-store
`$ git clone https://github.com/valery-barysok/session-file-store.git`
`$ cd session-file-store/examples/express-example`
`$ npm install`

## Install Test-Suite in example
`$ npm install --save-dev mocha supertest`

## Add test
`$ mkdir test && cd test && touch app.test.js`

app.test.js:
```js
var request = require('supertest');

describe("Test availability", function () {
    var server;
    before(function () {
        server = require('../app');
    });
    after(function () {
        server.close();
    });

    it("returns 200", function (done) {
        request(server)
            .get('/')
            .expect(200)
            .end(function (err, res) {
                if (err) return done(err);
                done();
            });

    });
});
```

## Modify app.js
```js
[...]
module.exports = server;
```

## Run test 
navigate back to session-file-store/examples/express-example

```
$ ./node_modules/.bin/mocha
Test availability
    ✓ returns 200


  1 passing (180ms)
  [...] stays forever in this process
```
# Without session-file-store
## Remove session-file-store from app.js
```js
var express = require('express');
var app = express();
var session = require('express-session');
var FileStore = require('session-file-store')(session);

app.get('/', function (req, res) {
  res.send('hi');
});

var server = app.listen(1337, function () {
  var host = server.address().address;
  var port = server.address().port;

  // console.log('Example app listening at http://%s:%s', host, port);
});

module.exports = server;
```
## Run same test 
navigate back to session-file-store/examples/express-example

```
$ ./node_modules/.bin/mocha
Test availability
    ✓ returns 200


  1 passing (180ms)

$ <-- prompt for new command
```

**Comment by valery-barysok** [comment]
@Tilogorn, can you check if reap worker run in the same time?

**Comment by Tilogorn** [comment]
@valery-barysok Nice hint, works! For everyone googling: Disabling the reap worker by setting the `reapInterval` to `-1` let the mocha-tests exit. 

```js
[...]
var FileStore = require('session-file-store')(session);

var fileStoreOptions = {
  reapInterval: -1,
};

app.use(session({
    store: new FileStore(fileStoreOptions),
    [...]
```
Can be closed :+1:
