### ISSUE TITLE
retrieve all current sessions all()

### ISSUE THREAD

**Issue by diginfo** [valery-barysok/session-file-store#75]
Is it possible to retrieve an arrany of all current sessions that I believe is normally implemented using the sessionStore.all() ?

I need to be able to get a count of existing logins and also be able to check whether the userid (stored in the session - session.userid) of a new login already exists in the store.

Thanks

**Comment by valery-barysok** [comment]
you can list session files with list() function.

**Comment by diginfo** [comment]
Thanks, but what is the exact syntax ??

I Tried 

FileStore('list');
FileStore.list() 

and they did not work ?

**Comment by valery-barysok** [comment]
should be something like this:

```
store.list(func (err, files) {
   ...
})
```

see details:
https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-helpers.js#L345
https://github.com/valery-barysok/session-file-store/blob/master/lib/session-file-store.js#L119

**Comment by diginfo** [comment]
Thanks so much, yes that works :-)
