### ISSUE TITLE
TypeError: Cannot set property 'cookie' of null

### ISSUE THREAD

**Issue by simmatrix** [valery-barysok/session-file-store#77]
It works perfectly fine until when I leave the website for a long period of time, later when I refresh the website, the NextJS app exited, with the following error printed on the console

```
        originalSession.cookie = session.cookie;
                               ^

TypeError: Cannot set property 'cookie' of null
```

**Affected file:** /node_modules/session-file-store/lib/session-file-helpers.js:249

Here's my configuration
```
import session from 'express-session';
import SessionFileStore from 'session-file-store';

const FileStore = SessionFileStore(session);
const maxAge = 60 * 60 * 1 * 1000; // 1 hour
const fallbackSessionFn = () => ({ token: '', decodedToken: {} });

return session({
  secret: 'xxx',
  saveUninitialized: true,
  store: new FileStore({
    fallbackSessionFn,
    path: '/tmp/sessions',
    secret: 'xxx',
    reapAsync: true,
    reapSyncFallback: true,
  }),
  resave: false,
  rolling: true,
  httpOnly: true,
  cookie: { maxAge },
});
```

**Comment by TrungRueta** [comment]
any update from this issue? i got same issue in my developing project. it work okey after login and session created. but leave amount 20 mins or more then reload page it will failed

**Comment by valery-barysok** [comment]
Can you check with 1.3.1 version? I just publish fix for this issue.
