### ISSUE TITLE
crypto issues

### ISSUE THREAD

**Issue by jas-** [valery-barysok/session-file-store#82]
[PR #81](https://github.com/valery-barysok/session-file-store/pull/81) addresses issues with the current crypto implementation.

Some issues;
1. Depreciated API calls
2. Defaults to a weak mode of AES; i.e. CBC & CTR vs. authenticated or AEAD modes such as OFB & GCM
3. Weak key derivation; i.e. hashing vs. using a key derivation function with unique salt

**Comment by valery-barysok** [comment]
thanks. published new version: 1.4.0
