### ISSUE TITLE
When secret key filled, decipher output not encoding to utf8?

### ISSUE THREAD

**Issue by Mariede** [valery-barysok/session-file-store#87]
Hi guys, I am using session-file-store very smoothly except when I need to read extended ASCII characters (like açaí ou Antônio) in req.session.

I found the problem to exists only when using the secret option to encrypt files. So, I guess the output (decoder) fails when it needs to write back extended ascii chars, much like when encripting utf8->hex and not decrypting hex -> utf8 back again.

I didn't find a way to set this option and look up for a solution. So a tried to use cbor and a personal cypher/decipher lib too, but again I couldn't find a way to make it run without errors at decoder.

Any help would be much appreciated. Thank you guys. =)

**Comment by valery-barysok** [comment]
Hi @Mariede,
can you provide exact configuration or better complete example. thanks.

**Comment by Mariede** [comment]
Hi @valery-barysok  asap

`
-- ------------------------------------------------------------------------------------------------------
-- Middleware session:
// ...
app.use (
	session (
		{
			name: 'cookie-name',
			store: new sessionFileStore (
				{
					logFn: err => {
						myLogger.logger('error', `session-file-store: ${(err)}`);
					},
					path: (__dirname + '/sessions'),
					encoding: 'utf8',
					retries: 5,
					secret: ['another secret'],
					ttl: 60 * 20
				}
			),
			secret: ['my secret'],
			resave: false,
			saveUninitialized: false,
			unset: 'destroy',
			rolling: true,
			cookie: {
				httpOnly: true,
				sameSite: true,
				secure: true, // https
				maxAge: 1000 * 60 * 20
			}
		}
	)
);
// ...
-- ------------------------------------------------------------------------------------------------------

-- ------------------------------------------------------------------------------------------------------
-- logon:
// ...
	let sess = req.session,
		sessWraper = 'user';

	if (sess[sessWraper] === null || typeof sess[sessWraper] !== 'object') {
		sess[sessWraper] = {};

		/* Session data */
		sess[sessWraper].id = 33;
		sess[sessWraper].nome = 'João da Graça';
		sess[sessWraper].email = 'joao@email.com';
		/* Session data */
	}
// ...
	return sess[sessWraper];
-- ------------------------------------------------------------------------------------------------------

-- ------------------------------------------------------------------------------------------------------
-- isLogged:
// ...
	let sess = req.session,
		sessWraper = 'user',
		fRet = false;

	if (sess) {
		if (typeof sess[sessWraper] === 'object' && sess[sessWraper] !== null) {
			fRet = sess[sessWraper];
		}
	}

	return fRet;
-- ------------------------------------------------------------------------------------------------------

-- ------------------------------------------------------------------------------------------------------
-- logout:
// ...
	let sess = req.session;

	if (sess) {
		sess.destroy (
			err => {
				if (err) {
					reject(err);
				} else {
					res.cookie('cookie-name', '', { expires: new Date() });
					resolve();
				}
			}
		);
	}
// ...
-- ------------------------------------------------------------------------------------------------------
`

I hope it helps. Please tell me if you need something else ok.


Thank you!

**Comment by jas-** [comment]
What version of session-file-store are you using?

**Comment by Mariede** [comment]
@jas-  latest

**Comment by jas-** [comment]
@Mariede can you provide a stack trace?

**Comment by Mariede** [comment]
Important to make clear that there is no error in any route calls. It is always 200. I will put 2 images, first right after /logon (data is displayed ok), then after /islogged (data starts to display compromised)

![image](https://user-images.githubusercontent.com/4501798/79033539-4bc09300-7b85-11ea-920e-11082c8a8137.png)
![image](https://user-images.githubusercontent.com/4501798/79033553-65fa7100-7b85-11ea-9f6b-7ed8038322ab.png)

**Comment by Mariede** [comment]
Now, after removing the "secret" key in options and consequently with the cipher/decipher not changing the session file, things are ok...

![image](https://user-images.githubusercontent.com/4501798/79033646-4c0d5e00-7b86-11ea-979a-694ab078e00b.png)

**Comment by jas-** [comment]
This is an input/output encoding issue with the binary encoded ciphertext in the kruptein library.

I will look at it right away

**Comment by jas-** [comment]
@Mariede hello again, I have pushed a fix in the `v2.0.8` branch of the [kruptein](https://github.com/jas-/kruptein/tree/v2.0.8) module.

Can you test it?

You can do so by going into the `node_modules/` folder of your project and removing the `kruptein` folder. Once you have done that you can either download and extract the zip file from [here](https://github.com/jas-/kruptein/archive/v2.0.8.zip) or you can simply clone the new branch like so; `git clone -b v2.0.8 --single-branch https://github.com/jas-/kruptein.git`.

Or you can always just copy the updated [file (kruptein.js)](https://github.com/jas-/kruptein/blob/v2.0.8/lib/kruptein.js) into the `node_modules/kruptein/lib` folder.

Once you have done that restart your app and test the sessions.

**Comment by Mariede** [comment]
Hi @jas- ! Yes, it worked like a charm! Thank you for the work! Will it be available for session-file-store in npm too?

![image](https://user-images.githubusercontent.com/4501798/79050383-0beac180-7c00-11ea-84ef-891d413dc2ab.png)

**Comment by jas-** [comment]
Now that I have outside confirmation, thanks by the way, I am building out some additional tests to ensure encoding formats are supported including the varying character sets. An updated package will be published in the next hour or two.

**Comment by jas-** [comment]
@Mariede @valery-barysok This is fixed in version `v2.0.8`.

**Comment by Mariede** [comment]
Thank you guys @jas- @valery-barysok 

With the new v2.0.8 the data displayed is ok now. I will close the issue.
