### ISSUE TITLE
Session are not persisting on restart

### ISSUE THREAD

**Issue by eavdmeer** [valery-barysok/session-file-store#90]
I am using an application with express, express-session and passport-ldapauth.

Everything works fine using session-file-store as a drop in replacement for [memorystore](https://www.npmjs.com/package/memorystore). I can see the session files being created correctly and I see the corresponding session ID in the cookies in the browser. I can navigate around and close and re-open the browser and the session is all fine.

Then, if I restart the server, passport immediately concludes that I'm no longer logged in. The session id is still passed correctly. Persistence of the session is the whole reason to go to a file store instead of memory.
````
const express = require('express');
const passport = require('passport');
const session = require('express-session');
const FileStore = require('session-file-store')(session);
const bodyParser = require('body-parser');
const LdapStrategy = require('passport-ldapauth');
const uniqid = require('uniqid');
const compression = require('compression');
....
  passport.use(new LdapStrategy({ server: ldapServer }));
  passport.serializeUser((user, done) =>
  {
    done(null, user);
  });
  passport.deserializeUser((user, done) =>
  {
    done(null, user);
  });
...
  app.use(compression({ threshold: 200 }));

  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));

  app.set('trust proxy', 1);
  app.use(session({
    name: cookieName,
    secret: uniqid(),
    resave: false,
    saveUninitialized: false,
    store: new FileStorle({ ttl: sessionLength }),
    cookie: { secure: 'auto', maxAge: sessionLength, sameSite: 'lax' }
  }));

  app.use(passport.initialize());
  app.use(passport.session());
```

**Comment by jas-** [comment]
When you restart your application the cookie secret is changed, `secret: uniqid()`, which invalidates the existing session.

**Comment by eavdmeer** [comment]
This would be me leaving with egg on my face.... Thank you so much for spotting that rather silly mistake!
